name: Workflows with large secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
          TEST_ENV: 123
        run: |
         echo "Hello $TEST_ENV! $LARGE_SECRET_PASSPHRASE"
